import type { Locale } from './i18n/dictionaries';

type WidenText<T> =
  T extends string ? string
    : T extends readonly (infer U)[] ? WidenText<U>[]
      : T extends object ? { -readonly [K in keyof T]: WidenText<T[K]> }
        : T;

export const BOOKING_COPY = {
  en: {
    pageEyebrow: 'STEP 2 OF 3',
    pageTitle: 'Dates and delivery address',
    pageDesc: 'Green days are available, red ones are already booked. Choose the rental period and add your delivery address.',
    noScooter: 'Choose a scooter from the catalog first.',
    selectedScooter: 'SELECTED SCOOTER',
    photo: 'PHOTO',
    changeScooter: 'Change scooter',
    timeTitle: 'PICKUP / RETURN TIME',
    startTime: 'Start time',
    endTime: 'End time',
    invalidRange: 'End date/time must be later than start date/time.',
    addressTitle: 'DELIVERY ADDRESS',
    addressLabel: 'Delivery address',
    addressPlaceholder: 'Villa, hotel, or exact delivery address',
    addressRequired: 'Enter the delivery address to continue.',
    promoCode: 'Promo code',
    optional: 'Optional',
    promoApplied: 'Applied — {amount} discount',
    promoInvalid: 'Invalid or expired promo code',
    discountLabel: 'Discount',
    addonsTitle: 'ADD-ONS',
    addonsHelp: 'Extra options can be added to the booking right away.',
    addonsUnavailable: 'Extra options are not available.',
    summaryTitle: 'STEP 2 SUMMARY',
    pickDates: 'Select dates in the calendar',
    datesNotSelected: 'Dates are not selected',
    noOptions: 'No options selected',
    base: 'Base',
    addons: 'Add-ons',
    delivery: 'Delivery',
    estimatedTotal: 'Estimated total',
    continueToPayment: 'Continue to payment',
    nextStepHint: 'On the next step you will choose the payment method.',
    calendarTitle: 'AVAILABILITY CALENDAR',
    legendAvailable: 'Available',
    legendBooked: 'Booked',
    legendSelected: 'Selected',
    loadAvailabilityFailed: 'Failed to load availability',
    pickEndDate: 'Selected {date} — click the end date.',
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    selectedAddons: '{n} add-ons · ${amount}',
  },
  ru: {
    pageEyebrow: 'ШАГ 2 ИЗ 3',
    pageTitle: 'Даты и адрес доставки',
    pageDesc: 'Зелёные дни свободны, красные уже заняты. Выберите период аренды и укажите адрес доставки.',
    noScooter: 'Сначала выберите скутер в каталоге.',
    selectedScooter: 'ВЫБРАННЫЙ СКУТЕР',
    photo: 'ФОТО',
    changeScooter: 'Изменить скутер',
    timeTitle: 'ВРЕМЯ ПОЛУЧЕНИЯ / ВОЗВРАТА',
    startTime: 'Время начала',
    endTime: 'Время окончания',
    invalidRange: 'Дата и время окончания должны быть позже начала.',
    addressTitle: 'АДРЕС ДОСТАВКИ',
    addressLabel: 'Адрес доставки',
    addressPlaceholder: 'Вилла, отель или точный адрес доставки',
    addressRequired: 'Укажите адрес доставки, чтобы перейти дальше.',
    promoCode: 'Промокод',
    optional: 'Необязательно',
    promoApplied: 'Применено — скидка {amount}',
    promoInvalid: 'Неверный или просроченный промокод',
    discountLabel: 'Скидка',
    addonsTitle: 'ДОПОЛНЕНИЯ',
    addonsHelp: 'Дополнительные опции можно добавить сразу к бронированию.',
    addonsUnavailable: 'Дополнительные опции недоступны.',
    summaryTitle: 'СВОДКА ШАГА 2',
    pickDates: 'Выберите даты в календаре',
    datesNotSelected: 'Даты не выбраны',
    noOptions: 'Опции не выбраны',
    base: 'База',
    addons: 'Допы',
    delivery: 'Доставка',
    estimatedTotal: 'Примерный итог',
    continueToPayment: 'Перейти к оплате',
    nextStepHint: 'На следующем шаге вы выберете способ оплаты.',
    calendarTitle: 'КАЛЕНДАРЬ ДОСТУПНОСТИ',
    legendAvailable: 'Свободно',
    legendBooked: 'Занято',
    legendSelected: 'Выбрано',
    loadAvailabilityFailed: 'Не удалось загрузить доступность',
    pickEndDate: 'Выбран {date} — нажмите на дату окончания.',
    weekdays: ['П', 'В', 'С', 'Ч', 'П', 'С', 'В'],
    selectedAddons: '{n} допов · ${amount}',
  },
  zh: {
    pageEyebrow: '第 2 步 / 共 3 步',
    pageTitle: '日期和送车地址',
    pageDesc: '绿色日期可用，红色日期已被预订。请选择租期并填写送车地址。',
    noScooter: '请先在车型页面选择一辆车。',
    selectedScooter: '已选车型',
    photo: '照片',
    changeScooter: '更换车型',
    timeTitle: '取车 / 还车时间',
    startTime: '开始时间',
    endTime: '结束时间',
    invalidRange: '结束日期和时间必须晚于开始时间。',
    addressTitle: '送车地址',
    addressLabel: '送车地址',
    addressPlaceholder: '别墅、酒店或准确地址',
    addressRequired: '请填写送车地址后再继续。',
    promoCode: '优惠码',
    optional: '可选',
    promoApplied: '已应用，优惠 {amount}',
    promoInvalid: '优惠码无效或已过期',
    discountLabel: '优惠',
    addonsTitle: '附加项',
    addonsHelp: '可以立即把附加项加入预订。',
    addonsUnavailable: '暂无附加项。',
    summaryTitle: '第 2 步摘要',
    pickDates: '请在日历中选择日期',
    datesNotSelected: '尚未选择日期',
    noOptions: '未选择附加项',
    base: '基础价',
    addons: '附加项',
    delivery: '送车',
    estimatedTotal: '预估总价',
    continueToPayment: '继续付款',
    nextStepHint: '下一步选择支付方式。',
    calendarTitle: '可用日期日历',
    legendAvailable: '可用',
    legendBooked: '已订',
    legendSelected: '已选',
    loadAvailabilityFailed: '加载可用日期失败',
    pickEndDate: '已选 {date}，请点击结束日期。',
    weekdays: ['一', '二', '三', '四', '五', '六', '日'],
    selectedAddons: '{n} 个附加项 · ${amount}',
  },
  id: {
    pageEyebrow: 'LANGKAH 2 DARI 3',
    pageTitle: 'Tanggal dan alamat pengantaran',
    pageDesc: 'Hari hijau tersedia, hari merah sudah dipesan. Pilih masa sewa dan isi alamat pengantaran.',
    noScooter: 'Pilih skuter dari katalog terlebih dahulu.',
    selectedScooter: 'SKUTER TERPILIH',
    photo: 'FOTO',
    changeScooter: 'Ganti skuter',
    timeTitle: 'WAKTU AMBIL / KEMBALI',
    startTime: 'Waktu mulai',
    endTime: 'Waktu selesai',
    invalidRange: 'Tanggal/waktu selesai harus setelah mulai.',
    addressTitle: 'ALAMAT PENGANTARAN',
    addressLabel: 'Alamat pengantaran',
    addressPlaceholder: 'Vila, hotel, atau alamat lengkap',
    addressRequired: 'Isi alamat pengantaran untuk melanjutkan.',
    promoCode: 'Kode promo',
    optional: 'Opsional',
    promoApplied: 'Berhasil dipakai — diskon {amount}',
    promoInvalid: 'Kode promo tidak valid atau sudah kedaluwarsa',
    discountLabel: 'Diskon',
    addonsTitle: 'TAMBAHAN',
    addonsHelp: 'Tambahan bisa langsung dimasukkan ke pesanan.',
    addonsUnavailable: 'Tambahan tidak tersedia.',
    summaryTitle: 'RINGKASAN LANGKAH 2',
    pickDates: 'Pilih tanggal di kalender',
    datesNotSelected: 'Tanggal belum dipilih',
    noOptions: 'Belum ada tambahan',
    base: 'Dasar',
    addons: 'Tambahan',
    delivery: 'Antar',
    estimatedTotal: 'Perkiraan total',
    continueToPayment: 'Lanjut ke pembayaran',
    nextStepHint: 'Pada langkah berikutnya Anda memilih metode pembayaran.',
    calendarTitle: 'KALENDER KETERSEDIAAN',
    legendAvailable: 'Tersedia',
    legendBooked: 'Dipesan',
    legendSelected: 'Dipilih',
    loadAvailabilityFailed: 'Gagal memuat ketersediaan',
    pickEndDate: 'Dipilih {date} — klik tanggal akhir.',
    weekdays: ['S', 'S', 'R', 'K', 'J', 'S', 'M'],
    selectedAddons: '{n} tambahan · ${amount}',
  },
  de: {
    pageEyebrow: 'SCHRITT 2 VON 3',
    pageTitle: 'Daten und Lieferadresse',
    pageDesc: 'Grüne Tage sind verfügbar, rote bereits gebucht. Wähle den Mietzeitraum und gib die Lieferadresse ein.',
    noScooter: 'Bitte zuerst einen Roller im Katalog wählen.',
    selectedScooter: 'AUSGEWÄHLTER ROLLER',
    photo: 'FOTO',
    changeScooter: 'Roller wechseln',
    timeTitle: 'ABHOL- / RÜCKGABEZEIT',
    startTime: 'Startzeit',
    endTime: 'Endzeit',
    invalidRange: 'Enddatum/-zeit muss nach dem Start liegen.',
    addressTitle: 'LIEFERADRESSE',
    addressLabel: 'Lieferadresse',
    addressPlaceholder: 'Villa, Hotel oder genaue Lieferadresse',
    addressRequired: 'Bitte Lieferadresse eingeben, um fortzufahren.',
    promoCode: 'Promocode',
    optional: 'Optional',
    promoApplied: 'Angewendet — {amount} Rabatt',
    promoInvalid: 'Promocode ist ungültig oder abgelaufen',
    discountLabel: 'Rabatt',
    addonsTitle: 'EXTRAS',
    addonsHelp: 'Extras können sofort zur Buchung hinzugefügt werden.',
    addonsUnavailable: 'Keine Extras verfügbar.',
    summaryTitle: 'SCHRITT-2-ZUSAMMENFASSUNG',
    pickDates: 'Bitte Daten im Kalender wählen',
    datesNotSelected: 'Keine Daten gewählt',
    noOptions: 'Keine Extras gewählt',
    base: 'Basis',
    addons: 'Extras',
    delivery: 'Lieferung',
    estimatedTotal: 'Geschätzte Summe',
    continueToPayment: 'Weiter zur Zahlung',
    nextStepHint: 'Im nächsten Schritt wählst du die Zahlungsmethode.',
    calendarTitle: 'VERFÜGBARKEITSKALENDER',
    legendAvailable: 'Verfügbar',
    legendBooked: 'Gebucht',
    legendSelected: 'Ausgewählt',
    loadAvailabilityFailed: 'Verfügbarkeit konnte nicht geladen werden',
    pickEndDate: '{date} gewählt — Enddatum anklicken.',
    weekdays: ['M', 'D', 'M', 'D', 'F', 'S', 'S'],
    selectedAddons: '{n} Extras · ${amount}',
  },
  fr: {
    pageEyebrow: 'ÉTAPE 2 SUR 3',
    pageTitle: 'Dates et adresse de livraison',
    pageDesc: 'Les jours verts sont disponibles, les rouges sont déjà réservés. Choisissez la période et ajoutez votre adresse.',
    noScooter: 'Choisissez d’abord un scooter dans le catalogue.',
    selectedScooter: 'SCOOTER SÉLECTIONNÉ',
    photo: 'PHOTO',
    changeScooter: 'Changer de scooter',
    timeTitle: 'HEURE DE PRISE / RETOUR',
    startTime: 'Heure de début',
    endTime: 'Heure de fin',
    invalidRange: 'La date/heure de fin doit être après le début.',
    addressTitle: 'ADRESSE DE LIVRAISON',
    addressLabel: 'Adresse de livraison',
    addressPlaceholder: 'Villa, hôtel ou adresse exacte',
    addressRequired: 'Veuillez saisir l’adresse de livraison pour continuer.',
    promoCode: 'Code promo',
    optional: 'Optionnel',
    promoApplied: 'Appliqué — remise de {amount}',
    promoInvalid: 'Code promo invalide ou expiré',
    discountLabel: 'Remise',
    addonsTitle: 'OPTIONS',
    addonsHelp: 'Les options peuvent être ajoutées immédiatement à la réservation.',
    addonsUnavailable: 'Aucune option disponible.',
    summaryTitle: 'RÉSUMÉ DE L’ÉTAPE 2',
    pickDates: 'Choisissez les dates dans le calendrier',
    datesNotSelected: 'Dates non choisies',
    noOptions: 'Aucune option choisie',
    base: 'Base',
    addons: 'Options',
    delivery: 'Livraison',
    estimatedTotal: 'Total estimé',
    continueToPayment: 'Continuer vers le paiement',
    nextStepHint: 'À l’étape suivante, vous choisirez le mode de paiement.',
    calendarTitle: 'CALENDRIER DE DISPONIBILITÉ',
    legendAvailable: 'Disponible',
    legendBooked: 'Réservé',
    legendSelected: 'Sélectionné',
    loadAvailabilityFailed: 'Impossible de charger la disponibilité',
    pickEndDate: '{date} sélectionné — cliquez sur la date de fin.',
    weekdays: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
    selectedAddons: '{n} options · ${amount}',
  },
} as const;

export type BookingExtraContent = WidenText<typeof BOOKING_COPY.en>;

export const PAYMENT_COPY = {
  en: {
    missingDetails: 'Booking details were not found. Please return to step 2.',
    cardNameRequired: 'Enter the cardholder name.',
    cardNumberInvalid: 'Card number looks invalid.',
    cardExpiryInvalid: 'Expiry date must be in MM/YY format.',
    cardCvcInvalid: 'CVC is invalid.',
    cashConsent: 'Please confirm payment on delivery.',
    draftMissing: 'Booking draft not found',
    guestRequired: 'Enter your name and phone to continue',
    bookingName: 'Scooter booking',
    topbar: 'STEP 3 OF 3 · PAYMENT',
    methodCard: 'Card',
    methodCash: 'Cash',
    methodCrypto: 'Crypto',
    messengerTelegram: 'Telegram',
    messengerWeChat: 'WeChat',
    messengerWhatsApp: 'WhatsApp',
    cryptoNetwork: 'TRC-20 / ERC-20',
    pageTitle: 'Payment and confirmation',
    reserved: 'BOOKING RESERVED',
    confirmed: 'RESERVATION CONFIRMED',
    reservedDesc: 'Your scooter is reserved. It is already visible in your profile and you can pay on delivery.',
    openProfile: 'Open profile',
    contactDetails: 'CONTACT DETAILS',
    alreadyHave: 'Already have an account? Sign in',
    messengerTitle: 'MESSENGERS ON THIS NUMBER',
    messengerHint: 'Mark where we can contact you faster about the booking.',
    reserveCash: 'Reserve (pay on delivery) →',
    payCrypto: 'Pay {currency} →',
    bookingLabel: 'BOOKING',
    base: 'Base',
    addons: 'Add-ons',
    discountLabel: 'Discount',
    paymentAdjustment: 'Payment method adjustment',
    bankCard: 'BANK CARD · STRIPE',
    bankCardDesc: 'After the booking is created, we will redirect you to a secure Stripe page to finish payment. This form is a preview.',
    cardholder: 'Cardholder name',
    cardNumber: 'Card number',
    cardExpiry: 'Expiry (MM/YY)',
    cashTitle: 'CASH ON DELIVERY',
    cashDesc: 'The courier will bring the scooter to the address provided. Pay in cash upon delivery (USD or IDR at the daily rate).',
    deliveryAddress: 'DELIVERY ADDRESS',
    noDelivery: 'You did not specify a delivery address on step 2. Go back and fill it in.',
    cashBullet1: 'Booking is confirmed immediately, free cancellation up to 24 hours before.',
    cashBullet2: 'Deposit on delivery: passport or refundable $100.',
    cashBullet3: 'Cash payment on the rental start day.',
    cashConfirm: 'I confirm that I am ready to pay in cash on delivery and will be available at the specified time.',
    cryptoTitle: 'CRYPTO PAYMENT',
    cryptoDesc: 'We will create an invoice with the crypto provider. After confirmation you will receive the wallet address and the amount due.',
    selectCurrency: 'SELECT CURRENCY',
    amount: 'AMOUNT',
    amountHint: 'the exact amount will be shown after the invoice is created',
  },
  ru: {
    missingDetails: 'Детали бронирования не найдены. Вернитесь к шагу 2.',
    cardNameRequired: 'Введите имя владельца карты.',
    cardNumberInvalid: 'Номер карты выглядит некорректно.',
    cardExpiryInvalid: 'Срок действия должен быть в формате MM/YY.',
    cardCvcInvalid: 'CVC указан некорректно.',
    cashConsent: 'Подтвердите оплату при доставке.',
    draftMissing: 'Черновик бронирования не найден',
    guestRequired: 'Введите имя и телефон, чтобы продолжить',
    bookingName: 'Бронирование скутера',
    topbar: 'ШАГ 3 ИЗ 3 · ОПЛАТА',
    methodCard: 'Карта',
    methodCash: 'Наличные',
    methodCrypto: 'Крипто',
    messengerTelegram: 'Telegram',
    messengerWeChat: 'WeChat',
    messengerWhatsApp: 'WhatsApp',
    cryptoNetwork: 'TRC-20 / ERC-20',
    pageTitle: 'Оплата и подтверждение',
    reserved: 'БРОНЬ СОЗДАНА',
    confirmed: 'БРОНЬ ПОДТВЕРЖДЕНА',
    reservedDesc: 'Ваш скутер забронирован. Он уже виден в профиле, а оплатить можно при доставке.',
    openProfile: 'Открыть профиль',
    contactDetails: 'КОНТАКТНЫЕ ДАННЫЕ',
    alreadyHave: 'Уже есть аккаунт? Войти',
    messengerTitle: 'МЕССЕНДЖЕРЫ НА ЭТОМ НОМЕРЕ',
    messengerHint: 'Отметьте, где с вами быстрее связаться по бронированию.',
    reserveCash: 'Зарезервировать (оплата при доставке) →',
    payCrypto: 'Оплатить {currency} →',
    bookingLabel: 'БРОНЬ',
    base: 'База',
    addons: 'Допы',
    discountLabel: 'Скидка',
    paymentAdjustment: 'Корректировка способа оплаты',
    bankCard: 'БАНКОВСКАЯ КАРТА · STRIPE',
    bankCardDesc: 'После создания брони мы перенаправим вас на безопасную страницу Stripe для завершения оплаты. Эта форма показывает предварительные данные.',
    cardholder: 'Имя владельца',
    cardNumber: 'Номер карты',
    cardExpiry: 'Срок (MM/YY)',
    cashTitle: 'ОПЛАТА ПРИ ДОСТАВКЕ',
    cashDesc: 'Курьер привезёт скутер по указанному адресу. Оплатите наличными при получении (USD или IDR по дневному курсу).',
    deliveryAddress: 'АДРЕС ДОСТАВКИ',
    noDelivery: 'Вы не указали адрес доставки на шаге 2. Вернитесь и заполните его.',
    cashBullet1: 'Бронь подтверждается сразу, бесплатная отмена за 24 часа.',
    cashBullet2: 'Депозит при получении: паспорт или возвратные 100$.',
    cashBullet3: 'Оплата наличными в день начала аренды.',
    cashConfirm: 'Я подтверждаю, что готов оплатить наличными при получении и обязуюсь быть на месте в указанное время.',
    cryptoTitle: 'КРИПТО-ОПЛАТА',
    cryptoDesc: 'Мы создадим инвойс через крипто-провайдера. После подтверждения вы получите адрес кошелька и сумму к оплате.',
    selectCurrency: 'ВЫБЕРИТЕ ВАЛЮТУ',
    amount: 'СУММА',
    amountHint: 'точная сумма будет показана после создания инвойса',
  },
  zh: {
    missingDetails: '未找到预订信息，请返回第 2 步。',
    cardNameRequired: '请输入持卡人姓名。',
    cardNumberInvalid: '银行卡号看起来无效。',
    cardExpiryInvalid: '有效期必须为 MM/YY 格式。',
    cardCvcInvalid: 'CVC 无效。',
    cashConsent: '请确认到付付款。',
    draftMissing: '未找到预订草稿',
    guestRequired: '请输入姓名和电话以继续',
    bookingName: '摩托预订',
    topbar: '第 3 步 / 共 3 步 · 支付',
    methodCard: '银行卡',
    methodCash: '现金',
    methodCrypto: '加密货币',
    messengerTelegram: 'Telegram',
    messengerWeChat: 'WeChat',
    messengerWhatsApp: 'WhatsApp',
    cryptoNetwork: 'TRC-20 / ERC-20',
    pageTitle: '支付与确认',
    reserved: '预订已创建',
    confirmed: '预订已确认',
    reservedDesc: '您的车辆已预留，可在个人资料中查看并在交付时付款。',
    openProfile: '打开资料',
    contactDetails: '联系信息',
    alreadyHave: '已有账户？登录',
    messengerTitle: '此号码可用的聊天软件',
    messengerHint: '勾选我们可以更快联系您的方式。',
    reserveCash: '预留（交付时付款）→',
    payCrypto: '支付 {currency} →',
    bookingLabel: '预订',
    base: '基础价',
    addons: '附加项',
    discountLabel: '优惠',
    paymentAdjustment: '支付方式调整',
    bankCard: '银行卡 · STRIPE',
    bankCardDesc: '创建预订后，我们会将您跳转到安全的 Stripe 页面完成付款。此表单仅为预览。',
    cardholder: '持卡人姓名',
    cardNumber: '卡号',
    cardExpiry: '有效期 (MM/YY)',
    cashTitle: '货到付款',
    cashDesc: '配送员会将车辆送到指定地址。交付时支付现金（USD 或按日汇率的 IDR）。',
    deliveryAddress: '送车地址',
    noDelivery: '您在第 2 步没有填写送车地址，请返回补充。',
    cashBullet1: '预订立即确认，24 小时前可免费取消。',
    cashBullet2: '交付时押金：护照或可退还 100 美元。',
    cashBullet3: '在租赁开始当天现金支付。',
    cashConfirm: '我确认会在交付时现金支付，并按时在指定地点等候。',
    cryptoTitle: '加密支付',
    cryptoDesc: '我们会通过加密支付服务创建账单。确认后您将收到钱包地址和应付金额。',
    selectCurrency: '选择币种',
    amount: '金额',
    amountHint: '创建账单后会显示准确金额',
  },
  id: {
    missingDetails: 'Detail pesanan tidak ditemukan. Kembali ke langkah 2.',
    cardNameRequired: 'Masukkan nama pemilik kartu.',
    cardNumberInvalid: 'Nomor kartu tampak tidak valid.',
    cardExpiryInvalid: 'Tanggal berlaku harus format MM/YY.',
    cardCvcInvalid: 'CVC tidak valid.',
    cashConsent: 'Harap konfirmasi pembayaran saat pengantaran.',
    draftMissing: 'Draft pesanan tidak ditemukan',
    guestRequired: 'Masukkan nama dan nomor telepon untuk melanjutkan',
    bookingName: 'Pemesanan skuter',
    topbar: 'LANGKAH 3 DARI 3 · PEMBAYARAN',
    methodCard: 'Kartu',
    methodCash: 'Tunai',
    methodCrypto: 'Kripto',
    messengerTelegram: 'Telegram',
    messengerWeChat: 'WeChat',
    messengerWhatsApp: 'WhatsApp',
    cryptoNetwork: 'TRC-20 / ERC-20',
    pageTitle: 'Pembayaran dan konfirmasi',
    reserved: 'PESANAN DIBUAT',
    confirmed: 'PESANAN DIKONFIRMASI',
    reservedDesc: 'Skuter Anda sudah dipesan. Sudah terlihat di profil dan bisa dibayar saat pengantaran.',
    openProfile: 'Buka profil',
    contactDetails: 'DETAIL KONTAK',
    alreadyHave: 'Sudah punya akun? Masuk',
    messengerTitle: 'MESSENGER DI NOMOR INI',
    messengerHint: 'Centang aplikasi yang bisa kami pakai untuk menghubungi Anda lebih cepat.',
    reserveCash: 'Pesan (bayar saat antar) →',
    payCrypto: 'Bayar {currency} →',
    bookingLabel: 'PESANAN',
    base: 'Dasar',
    addons: 'Tambahan',
    discountLabel: 'Diskon',
    paymentAdjustment: 'Penyesuaian metode pembayaran',
    bankCard: 'KARTU BANK · STRIPE',
    bankCardDesc: 'Setelah pesanan dibuat, kami akan mengarahkan Anda ke halaman Stripe yang aman untuk menyelesaikan pembayaran. Formulir ini hanya pratinjau.',
    cardholder: 'Nama pemilik kartu',
    cardNumber: 'Nomor kartu',
    cardExpiry: 'Masa berlaku (MM/YY)',
    cashTitle: 'BAYAR SAAT ANTAR',
    cashDesc: 'Kurir akan membawa skuter ke alamat yang diberikan. Bayar tunai saat diterima (USD atau IDR sesuai kurs harian).',
    deliveryAddress: 'ALAMAT PENGANTARAN',
    noDelivery: 'Anda belum mengisi alamat pengantaran pada langkah 2. Kembali dan lengkapi.',
    cashBullet1: 'Pesanan langsung dikonfirmasi, pembatalan gratis hingga 24 jam sebelumnya.',
    cashBullet2: 'Deposit saat terima: paspor atau US$100 refundable.',
    cashBullet3: 'Pembayaran tunai pada hari mulai sewa.',
    cashConfirm: 'Saya mengonfirmasi siap membayar tunai saat pengantaran dan akan berada di lokasi pada waktu yang ditentukan.',
    cryptoTitle: 'PEMBAYARAN KRIPTO',
    cryptoDesc: 'Kami akan membuat invoice melalui penyedia kripto. Setelah konfirmasi Anda akan menerima alamat wallet dan jumlah pembayaran.',
    selectCurrency: 'PILIH MATA UANG',
    amount: 'JUMLAH',
    amountHint: 'jumlah tepat akan ditampilkan setelah invoice dibuat',
  },
  de: {
    missingDetails: 'Buchungsdetails wurden nicht gefunden. Bitte zu Schritt 2 zurückkehren.',
    cardNameRequired: 'Bitte Namen des Karteninhabers eingeben.',
    cardNumberInvalid: 'Kartennummer scheint ungültig zu sein.',
    cardExpiryInvalid: 'Ablaufdatum muss im Format MM/YY sein.',
    cardCvcInvalid: 'CVC ist ungültig.',
    cashConsent: 'Bitte Zahlung bei Lieferung bestätigen.',
    draftMissing: 'Buchungsentwurf nicht gefunden',
    guestRequired: 'Bitte Name und Telefonnummer eingeben, um fortzufahren',
    bookingName: 'Rollerbuchung',
    topbar: 'SCHRITT 3 VON 3 · ZAHLUNG',
    methodCard: 'Karte',
    methodCash: 'Bar',
    methodCrypto: 'Krypto',
    messengerTelegram: 'Telegram',
    messengerWeChat: 'WeChat',
    messengerWhatsApp: 'WhatsApp',
    cryptoNetwork: 'TRC-20 / ERC-20',
    pageTitle: 'Zahlung und Bestätigung',
    reserved: 'BUCHUNG ERSTELLT',
    confirmed: 'BUCHUNG BESTÄTIGT',
    reservedDesc: 'Dein Roller ist reserviert. Er ist bereits im Profil sichtbar und kann bei Lieferung bezahlt werden.',
    openProfile: 'Profil öffnen',
    contactDetails: 'KONTAKTDATEN',
    alreadyHave: 'Schon ein Konto? Anmelden',
    messengerTitle: 'MESSENGER AUF DIESER NUMMER',
    messengerHint: 'Markiere, über welche Apps wir dich zur Buchung schneller erreichen können.',
    reserveCash: 'Reservieren (bei Lieferung zahlen) →',
    payCrypto: '{currency} bezahlen →',
    bookingLabel: 'BUCHUNG',
    base: 'Basis',
    addons: 'Extras',
    discountLabel: 'Rabatt',
    paymentAdjustment: 'Anpassung der Zahlungsart',
    bankCard: 'BANKKARTE · STRIPE',
    bankCardDesc: 'Nach Erstellung der Buchung leiten wir dich zur sicheren Stripe-Seite weiter. Dieses Formular ist nur eine Vorschau.',
    cardholder: 'Name des Karteninhabers',
    cardNumber: 'Kartennummer',
    cardExpiry: 'Ablauf (MM/YY)',
    cashTitle: 'ZAHLUNG BEI LIEFERUNG',
    cashDesc: 'Der Kurier bringt den Roller an die angegebene Adresse. Bezahle bar bei Übergabe (USD oder IDR zum Tageskurs).',
    deliveryAddress: 'LIEFERADRESSE',
    noDelivery: 'Du hast in Schritt 2 keine Lieferadresse angegeben. Bitte zurückgehen und ergänzen.',
    cashBullet1: 'Buchung wird sofort bestätigt, kostenlose Stornierung bis 24 Stunden vorher.',
    cashBullet2: 'Kaution bei Übergabe: Reisepass oder rückzahlbare 100 $.',
    cashBullet3: 'Barzahlung am ersten Miettag.',
    cashConfirm: 'Ich bestätige, dass ich bei Lieferung bar bezahlen werde und zur angegebenen Zeit vor Ort bin.',
    cryptoTitle: 'KRYPTOZAHLUNG',
    cryptoDesc: 'Wir erstellen eine Rechnung über den Krypto-Anbieter. Nach der Bestätigung erhältst du Wallet-Adresse und Betrag.',
    selectCurrency: 'WÄHRUNG WÄHLEN',
    amount: 'BETRAG',
    amountHint: 'der genaue Betrag wird nach Erstellung der Rechnung angezeigt',
  },
  fr: {
    missingDetails: 'Les détails de réservation sont introuvables. Revenez à l’étape 2.',
    cardNameRequired: 'Veuillez saisir le nom du titulaire.',
    cardNumberInvalid: 'Le numéro de carte semble invalide.',
    cardExpiryInvalid: 'La date d’expiration doit être au format MM/YY.',
    cardCvcInvalid: 'Le CVC est invalide.',
    cashConsent: 'Veuillez confirmer le paiement à la livraison.',
    draftMissing: 'Brouillon de réservation introuvable',
    guestRequired: 'Saisissez votre nom et votre téléphone pour continuer',
    bookingName: 'Réservation du scooter',
    topbar: 'ÉTAPE 3 / 3 · PAIEMENT',
    methodCard: 'Carte',
    methodCash: 'Espèces',
    methodCrypto: 'Crypto',
    messengerTelegram: 'Telegram',
    messengerWeChat: 'WeChat',
    messengerWhatsApp: 'WhatsApp',
    cryptoNetwork: 'TRC-20 / ERC-20',
    pageTitle: 'Paiement et confirmation',
    reserved: 'RÉSERVATION CRÉÉE',
    confirmed: 'RÉSERVATION CONFIRMÉE',
    reservedDesc: 'Votre scooter est réservé. Il est déjà visible dans votre profil et vous pourrez payer à la livraison.',
    openProfile: 'Ouvrir le profil',
    contactDetails: 'COORDONNÉES',
    alreadyHave: 'Déjà un compte ? Se connecter',
    messengerTitle: 'MESSAGERIES SUR CE NUMÉRO',
    messengerHint: 'Cochez les apps sur lesquelles nous pouvons vous joindre plus vite.',
    reserveCash: 'Réserver (payer à la livraison) →',
    payCrypto: 'Payer {currency} →',
    bookingLabel: 'RÉSERVATION',
    base: 'Base',
    addons: 'Options',
    discountLabel: 'Remise',
    paymentAdjustment: 'Ajustement du mode de paiement',
    bankCard: 'CARTE BANCAIRE · STRIPE',
    bankCardDesc: 'Après création de la réservation, nous vous redirigerons vers une page Stripe sécurisée pour terminer le paiement. Ce formulaire est un aperçu.',
    cardholder: 'Nom du titulaire',
    cardNumber: 'Numéro de carte',
    cardExpiry: 'Expiration (MM/YY)',
    cashTitle: 'PAIEMENT À LA LIVRAISON',
    cashDesc: 'Le coursier apportera le scooter à l’adresse indiquée. Payez en espèces à la livraison (USD ou IDR au taux du jour).',
    deliveryAddress: 'ADRESSE DE LIVRAISON',
    noDelivery: 'Vous n’avez pas indiqué d’adresse de livraison à l’étape 2. Revenez en arrière pour la renseigner.',
    cashBullet1: 'La réservation est confirmée immédiatement, annulation gratuite jusqu’à 24 h avant.',
    cashBullet2: 'Dépôt à la livraison : passeport ou 100 $ remboursables.',
    cashBullet3: 'Paiement en espèces le jour du début de location.',
    cashConfirm: 'Je confirme être prêt à payer en espèces à la livraison et à être présent à l’heure indiquée.',
    cryptoTitle: 'PAIEMENT CRYPTO',
    cryptoDesc: 'Nous créerons une facture via le prestataire crypto. Après confirmation, vous recevrez l’adresse du portefeuille et le montant à payer.',
    selectCurrency: 'CHOISIR LA DEVISE',
    amount: 'MONTANT',
    amountHint: 'le montant exact sera affiché après création de la facture',
  },
} as const;

export type PaymentExtraContent = WidenText<typeof PAYMENT_COPY.en>;

const FOOTER_EXTRA_COPY = {
  whatsappButton: 'WhatsApp · +62 813-5915-173',
  metaLine: 'BALI-RENT · JL. PANTAI BERAWA · CANGGU 80361 · LIC. 04/2019 · © 2026',
  localesLine: 'EN · ID · RU · DE · FR · ZH',
};

export const SITE_CONTENT_EXTRAS: Record<
  Locale,
  { booking: Record<string, unknown>; payment: Record<string, unknown>; footer: Record<string, unknown> }
> = {
  en: { booking: BOOKING_COPY.en, payment: PAYMENT_COPY.en, footer: FOOTER_EXTRA_COPY },
  ru: { booking: BOOKING_COPY.ru, payment: PAYMENT_COPY.ru, footer: FOOTER_EXTRA_COPY },
  zh: { booking: BOOKING_COPY.zh, payment: PAYMENT_COPY.zh, footer: FOOTER_EXTRA_COPY },
  id: { booking: BOOKING_COPY.id, payment: PAYMENT_COPY.id, footer: FOOTER_EXTRA_COPY },
  de: { booking: BOOKING_COPY.de, payment: PAYMENT_COPY.de, footer: FOOTER_EXTRA_COPY },
  fr: { booking: BOOKING_COPY.fr, payment: PAYMENT_COPY.fr, footer: FOOTER_EXTRA_COPY },
};
